version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql
#      user: mysql #remove comment if you run with MAC and has error with docker-compose
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=homestead
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      volumes:
        - ./data:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        zenlock:
          ipv4_address: 172.18.0.2

    php-fpm:
      build: phpdocker/php
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./phpdocker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./qa-test:/application
      networks:
        zenlock:
          ipv4_address: 172.18.0.5

    webserver:
      build: phpdocker/nginx
      image: servercontainers/nginx
      restart: always
      container_name: webserver
      working_dir: /application
      volumes:
        - ./qa-test:/application
      ports:
        - 8000:80
        - 8443:443
      networks:
        zenlock:
          ipv4_address: 172.18.0.3

    redis:
      image: redis:4.0.5-alpine
      hostname: redis
      ports:
        - 6379:6379
      networks:
         zenlock:
           ipv4_address: 172.18.0.8
      volumes:
        - ./redis:/data

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - 8003:80
      environment:
        PMA_USER: homestead
        PMA_PASSWORD: secret
        PMA_HOST: 172.18.0.2
      networks:
        zenlock:
          ipv4_address: 172.18.0.4


networks:
  zenlock:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/24
